### ISSUE TITLE
讨论module设计

### ISSUE THREAD

**Issue by NicholeGit** [name5566/leaf#1]
- module为啥不用map管理 不需要快速找到模块吗？
- 为啥不给每个module加一个channel通过这个来做通讯

**Comment by name5566** [comment]
补充一下，现在已经去掉了 util.CallRouter，使用 chanrpc 代替。

**Comment by go-wolf** [comment]
我在login模块 用 login.chanrpc.go() 然后在game 里面用  game.chanrpc.go()   import cycle not allowed错误 怎么用呢

**Comment by name5566** [comment]
> 我在login模块 用 login.chanrpc.go() 然后在game 里面用 game.chanrpc.go() import cycle not allowed错误 怎么用呢

详见：https://github.com/name5566/leaf/blob/master/TUTORIAL_ZH.md#leaf-%E6%A8%A1%E5%9D%97%E8%AF%A6%E8%A7%A3
