### ISSUE TITLE
请问下，为什么Protobuf的MsgID不直接用从客户端传过来的，而要再新建一个reflect.type和自增ID的对应map来映射呢？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#100]
谢谢回答

**Comment by name5566** [comment]
msg id 不是 protobuf 的一部分。详细看一下：https://github.com/name5566/leaf/wiki/%E5%9C%A8-Leaf-%E4%B8%AD%E4%BD%BF%E7%94%A8-Protobuf

**Comment by jjjjilyf** [comment]
谢谢回答
