### ISSUE TITLE
请问下Processor在处理Route时，为什么要分开MsgRaw和MsgInfo，这两个结构体有什么区别啊？谢谢回答

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#101]
MsgRaw和MsgInfo分别再什么时候用啊？全部用MsgInfo不行吗？

**Comment by name5566** [comment]
这个需要你看代码才能明白细节。Processor 提供了 Raw Handler（为了解决分布式服务的问题），通过这个 handler 可以拿到原始的消息数据（而非解析后的消息数据）。

**Comment by jjjjilyf** [comment]
哦 这样啊 现在有个问题是 我想用FlatBuffer做通讯协议，但是FlatBuffer没有像ProtoBuffer的Proto.Marshal和Proto.UnMarshal这两步，意味着在Processor里也不能实现这两步，FlatBuffer里是用 People.getRootAsPeople(buffer);这样直接取得对象的（所以FlatBuffer不同的类对象的获取方法也不相同，不像ProtoBuffer的一个Proto.UnMarshal能够通用处理），请问下，在这种情况下 是不是就是用这种MsgRaw的情况了？拿到的是原始数据byte[]而不是解析后的 Msg,这样的话 如果我要从gate服传到login服里也要重新定义Chan的类型吧 byte[]类型，是这样吗？我这样表述问题清楚吗？谢谢回答

**Comment by name5566** [comment]
感觉你的理解不太对，你可以再看几遍代码，如果不明白也可以看看 JSON Processor 的代码

**Comment by jjjjilyf** [comment]
那我再看一下 3Q

**Comment by jjjjilyf** [comment]
看了一下，把FlatBuffer加入成功了。因为FlatBuffer不需要Marshal和Unmarshal，我在注册消息的时候，给消息添加了rawMsgHandler，这样Route的时候就进入了rawMsgHandler的处理里，在rawMsgHandler里，把数据发送到其他服务器(和Route后面的处理一样,chanrpc.GO).其实在Marshal和Unmarshal里只是把ID和Flatbuffers.Flatbuffer(相当于proto.message)分离了出来，其他没做任何处理，实际的处理是在目标服务器的接受数据函数里处理，因为FlatBuffer里每个类的初始化函数不同，比如A的就是getRootAsA,B的就是getRootAsB.
