### ISSUE TITLE
请问我服务器要在Login时做验证，在Game里保存数据，跟数据库的处理是怎样的？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#103]
1.是Login和Game都保持一个MongoDB的连接吗？
Login就是登录验证和创建角色。
Game保存玩家获得的道具，分数等。
这样Login和Game两个MongoDB的连接连接一个MongoDB会不会有冲突？
还是把Login的创建角色处理放在Game里Login只做查询，不操作DB的数据？

2.还有就是我在Login里验证过后，就通过chanrpc通知Game创建玩家实体，如果玩家实体不存在，不管收到了Gate转发到Game的任何消息，如果实体不存在就说明玩家没有验证过，就不处理该消息，用这种方式来保证消息安全，目前想到的只有这一种方法,可行吗？有没有更好的方法在Gate转发的时候就能确保消息的安全性呢？

3.DBServer单独独立出来做一个服务器呢？还是和Game放在一起？我看大神你在Leaf的中文文档里建议，不要划分太多模块，不要太频繁使用rpc通讯。要多在模块内部调用goroutine。虽然有这个建议，还是不知道应该怎么用起来比较好。

按照目前的设想

                 Login     (也要连接Redis)                   
           /                \                                 
Gate------------------Game-----------------DBServer------------Redis

**Comment by name5566** [comment]
角色相关的，包括创建，可以都放在 Game 模块。Login 应该只处理账号相关的事情，和游戏逻辑应该完全无关才对。

**Comment by name5566** [comment]
另外使用 Redis 不知道是有什么需求？

**Comment by jjjjilyf** [comment]
谢谢大神回答。
1.Redis连Login存放自己服务器生成的Token和微信的OpenID的Hash（设置过期时间），来确保玩家的Session有效性。
2.Redis连Game是因为Game有一个匹配不在线玩家的功能，匹配了玩家然后 用玩家数据使用AI来对战。想的是从Game定期检测Redis中的玩家数据，数据低于某个阈值，就从DB读取玩家数据到Redis，秒此匹配从Redis读取，不查数据库。
3.前面的回答让我明白了，Login只验证，Game才创建实体。谢谢回答。

**Comment by name5566** [comment]
放在 redis 中的数据，是否可以直接放在 game 里面？

**Comment by jjjjilyf** [comment]
应该是可以的，不过我看大家都用Redis，我这里也想尝试着用一下，不然感觉不上档次。。。
