### ISSUE TITLE
请问一下我在Login和Game里都需要访问同一个数据库

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#104]
请问一下我在Login和Game里都需要访问同一个数据库（Login只读取DB，Game读取+写DB），
是新建一个DBServer专门处理好Login和Game发来的DB请求，再返回给Login和Game结果好。
还是Login和Game都持有一个DB的连接格子处理DB的请求好？
谢谢回答

**Comment by jjjjilyf** [comment]
数据库的这块介绍的有点少，请大神给个思路，顺便给后来人铺路

**Comment by name5566** [comment]
可以直接连接 DB。具体按需求来处理。一般 Login 和 Game 不会使用同一个数据库。

**Comment by jjjjilyf** [comment]
收到，谢谢回答。
