### ISSUE TITLE
skeleton.AfterFunc

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#106]
用skeleton.AfterFunc ，1个timer定时处理 所有用户的数据，其中1个出错。结果这个timer，就停了，所有用户都不处理了。

有没有办法让其他的用户依然能处理？

**Comment by name5566** [comment]
你可以按你代码逻辑具体情况加入 recover

**Comment by 15951836388** [comment]
我看leaf的timer和go和chanrpc里都已经处理了recover，为什么还要额外处理？

但是似乎只有通过proto消息调用的方法，出错不会全挂掉。其他不行，这是为什么？

**Comment by karllynnn** [comment]
你这个出错是panic了吧，那是代码逻辑有问题。正常业务数据怎么会panic掉，在timer里面调用`defer skeleton.AfterFunc`，就能保证timer不会停掉

**Comment by 15951836388** [comment]
是数据错了，panic了。但是我的测试，timer确实停了。不知道要怎么改，测试代码如下：
下面代码执行10次，分母就为0了，会panic，timer就停了。希望timer可以不停止。不能因为1个用户出错，所有用户都不处理了。比如类似 整体回蓝的功能，1个用户出错，所有的用户都不能回蓝了

var a = 0

func test() {
	defer skeleton.AfterFunc(1*time.Millisecond, func() {
		a++
		b := 5 / (a - 10)
		log.Debug("ba", b, a)
		test()
	})
}

func init() {
	test()
}

**Comment by 15951836388** [comment]
glo.go:99: [debug  ] ba%!(EXTRA int=0, int=1)
glo.go:99: [debug  ] ba%!(EXTRA int=0, int=2)
glo.go:99: [debug  ] ba%!(EXTRA int=0, int=3)
glo.go:99: [debug  ] ba%!(EXTRA int=0, int=4)
glo.go:99: [debug  ] ba%!(EXTRA int=-1, int=5)
glo.go:99: [debug  ] ba%!(EXTRA int=-1, int=6)
glo.go:99: [debug  ] ba%!(EXTRA int=-1, int=7)
glo.go:99: [debug  ] ba%!(EXTRA int=-2, int=8)
glo.go:99: [debug  ] ba%!(EXTRA int=-5, int=9)
timer.go:39: [error  ] runtime error: integer divide by zero: goroutine 55 [running]:
github.com/name5566/leaf/timer.(*Timer).Cb.func1(0xc4200b0e40)
	/Users/yuanxuhui/Documents/go/src/github.com/name5566/leaf/timer/timer.go:38 +0xea
panic(0x14cb2e0, 0x195b040)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/15951836388/fjsg/game/internal.test.func1()
	/Users/yuanxuhui/Documents/go/src/github.com/15951836388/fjsg/game/internal/glo.go:98 +0x111
github.com/name5566/leaf/timer.(*Timer).Cb(0xc4200b0e40)
	/Users/yuanxuhui/Documents/go/src/github.com/name5566/leaf/timer/timer.go:47 +0x66
github.com/name5566/leaf/module.(*Skeleton).Run(0xc4203ee190, 0xc4200800e0)
	/Users/yuanxuhui/Documents/go/src/github.com/name5566/leaf/module/skeleton.go:65 +0x22e
github.com/name5566/leaf/module.run(0xc4204dec00)
	/Users/yuanxuhui/Documents/go/src/github.com/name5566/leaf/module/module.go:54 +0x3c
created by github.com/name5566/leaf/module.Init
	/Users/yuanxuhui/Documents/go/src/github.com/name5566/leaf/module/module.go:40 +0xa6

**Comment by name5566** [comment]
如果你的代码出错了，错误是一定可以被 Leaf 捕获到的。但是，你需要按特定规则去执行的你代码，是需要自己按需求去处理 panic 的。就像你上面这个例子，不是 timer 停止了，timer 本身只能执行一次，你的问题在于你无法再次启用 timer（也就是 test 没有被调用）。所以，这个问题还是如果用好 defer panic 的问题，你在代码中要保证无论有什么情况发生，都需要执行 test。
