### ISSUE TITLE
请问框架go.go里的LinearContext，Go，LinearGo结构体是用来做什么的？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#107]
谢谢回答

**Comment by name5566** [comment]
用于处理保证执行顺序的情况。具体看看例子：https://github.com/name5566/leaf/blob/master/go/example_test.go 就明白了。

**Comment by jjjjilyf** [comment]
收到，我看看先，O(∩_∩)O谢谢回答。
