### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by long0419** [name5566/leaf#109]
专业游戏公司 请问现在leaf 框架正式上线的游戏有哪些

**Comment by chiuan** [comment]
啥游戏都能做.

**Comment by long0419** [comment]
感觉这个是个半成品

**Comment by trazyn** [comment]
半成品都算不上的 demo 吧，你还当真了？

**Comment by name5566** [comment]
何来半成品一说。leaf 功能完善并已经有多款上线游戏，游戏开发者出于各种原因不愿意或未公开，这是每个用户的自由。目前的分布式支持并非完全必要的，并且是用户可以自由扩展的（leaf 内部提供了支持），实际使用中自己定义分布式架构也没有什么大问题。

**Comment by zcwtop** [comment]
提问者想的是希望提供一个有完整游戏逻辑的demo给他参考，包括登录注册，数据库，数据管理，开房，战斗等等等。leafSever只是一个大概，很多逻辑可能不知道如何写，才觉得是一个半成品吧。

**Comment by name5566** [comment]
注册是业务逻辑相关的，实际情况可能是账号管理是第三方的，比如说 QQ 登录啥的，也可能是自己实现的一套账号管理，这种不属于框架应该提供的功能。数据库，提供了支持，数据管理，提供了支持。开房和战斗，这种是纯粹的游戏逻辑，不是所有游戏都有开房，每个游戏的战斗也不一样。

所谓的想提供所有功能的人，大概是想直接提供一个完整游戏给他吧。

**Comment by long0419** [comment]
这个什么时候放到K8S 里面
