### ISSUE TITLE
请问skeleton.CronFunc(cronExpr, 是怎么用的？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#110]
cronExpr, err := timer.NewCronExpr("1 * * * * *")创建这个不是1秒钟 查询一次的意思吗？

**Comment by jjjjilyf** [comment]
谢谢回答，我看了一下 md文件，那个test里的代码
func ExampleTimer() {
	d := timer.NewDispatcher(10)

	// timer 1
	d.AfterFunc(1, func() {
		fmt.Println("My name is Leaf")
	})

	// timer 2
	t := d.AfterFunc(1, func() {
		fmt.Println("will not print")
	})
	t.Stop()

	// dispatch
	(<-d.ChanTimer).Cb()

	// Output:
	// My name is Leaf
}

如果不调用 (<-d.ChanTimer).Cb() 是不是就不执行了，如果没有stop呢？也不执行吧？没看到有从d.ChanTimer向外读取的地方啊？

**Comment by jjjjilyf** [comment]
func (g *Go) Go(f func(), cb func()) {
	g.pendingGo++

	go func() {
		defer func() {
			g.ChanCb <- cb
			if r := recover(); r != nil {
				if conf.LenStackBuf > 0 {
					buf := make([]byte, conf.LenStackBuf)
					l := runtime.Stack(buf, false)
					log.Error("%v: %s", r, buf[:l])
				} else {
					log.Error("%v", r)
				}
			}
		}()

		f()
	}()
}

btw黑体部分是什么意思呢

**Comment by name5566** [comment]
使用 skeleton 来使用 cron。

**Comment by jjjjilyf** [comment]
Entry	Description	Equivalent to
@yearly (or @annually)	Run once a year at midnight of 1 January	0 0 1 1 *
@monthly	Run once a month at midnight of the first day of the month	0 0 1 * *
@weekly	Run once a week at midnight on Sunday morning	0 0 * * 0
@daily	Run once a day at midnight	0 0 * * *
@hourly	Run once an hour at the beginning of the hour	0 * * * *
@reboot	Run at startup	N/A

NoTHX :|)
