### ISSUE TITLE
请问recordFile如果要用csv文件格式，和txt相比需要做什么改动？支持结构体数组吗？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#113]
谢谢回答

**Comment by jjjjilyf** [comment]
CSData.csv: parse error on line 2, column 2: bare " in non-quoted-field 
默认所处阶段,tt
1,"[1, 2]"
解析不了

**Comment by jjjjilyf** [comment]
CSData.csv: parse error on line 2, column 2: bare " in non-quoted-field 
默认所处阶段,tt
1,"[1, 2]"
解析不了

**Comment by jjjjilyf** [comment]
自己乱试试了出来，只能用csv导出的txt文件格式，且要自己转码到utf-8 bom格式。。。。。
但是那个txt格式 是用golang程序导出的 还是自己在csv表格里手动写好 struct array 用和struct 中字段后的flag一一对应，这样生成的 然后导出txt后缀的文件？？谢谢回答

**Comment by name5566** [comment]
leaf 读取 CSV 文件是使用 golang 标准库读取，可以参考 golang 标准库文档。

需要注意的地方是，CSV 文件的分隔符是 tab 还是 "," 等，这个 leaf 的 recordfile 可以配置，excel 导出液有说明。文件后缀是 txt 还是 csv 没有关系。

**Comment by jjjjilyf** [comment]
原来是这样！因为csv用wps导出 默认就是“，”作为分隔符，而txt用wps导出是“tab”作为分隔符，因为“，”要在数组和结构体里 分割属性和字段，所以这里明显就不能使用“，”作为表格的列分隔符了，只能用tab了，而以txt格式导出后 恰巧是tab作为分隔符。这样就和作为结构体和数组元素之间的分隔符“，”全分开了，不然会导致解析失败。
看RecordFile里的代码 
func (rf *RecordFile) Read(name string) error {
	file, err := os.Open(name)
	if err != nil {
		return err
	}
	defer file.Close()

	if rf.Comma == 0 {
		rf.Comma = Comma
	}
	if rf.Comment == 0 {
		rf.Comment = Comment
	}

在这里给赋值为comma '\t'的，确实可以自己配置.
多谢大神回答，节日快乐~~

**Comment by jjjjilyf** [comment]
顺便补充一点 为后来的人提供方便，如果在结构体后面有多个flag的话，将没有明确flag类型解析的放在··里第一个位置，··是键盘esc之下的键。
例如以下结构，如果“pos”没放在第一位，那再recordfile里就会解析不到数据，但是并不会报语法错误。
// 阵容位置上对应的上阵玩家ID
type PlayerPos struct {
	Pos 		byte	`"pos" 		json:"Pos" 		bson:"pos"`			// 阵容位置
	PlayerID	uint32	`"playerid" json:"PlayerID" bson:"playerid"`	// 玩家ID
}

**Comment by jjjjilyf** [comment]
再补充一下，不用转换格式用 wps打开csv文件 只要数据格式正确，直接另存为制表符txt格式就可以直接使用。
这里
给出一个 结构体数组的正确数据格式:[{"pos":0,"playerid":400101},{"pos":1,"playerid":400101}]
注意数组元素之间要用","隔开，";"会报错。
