### ISSUE TITLE
请问下是不是在执行 go test的时候 也会默认执行包里包含的init()函数

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#115]
这样的话 因为test好像不能使用WorkSpace到server/bin目录，所以找不到server.json而在conf里报错。
那么XX_test.go应该写在哪里呢？

**Comment by name5566** [comment]
一般来说，游戏开发 _test 用的不多。

**Comment by jjjjilyf** [comment]
谢谢回答
