### ISSUE TITLE
请问下mongodb的db.Ref建立了好多和MongoDB的连接，只有一个玩家，不应该只建立少量连接吗？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#116]
![image](https://user-images.githubusercontent.com/7004409/44700214-97aaeb00-aaba-11e8-8461-cb1f91e3fa2c.png)

**Comment by name5566** [comment]
实际连接数是可以配置的。

**Comment by jjjjilyf** [comment]
![image](https://user-images.githubusercontent.com/7004409/44700750-77306000-aabd-11e8-94f3-53ab4d7ad9a2.png)
请问是这里吗？如果配置的太少比如50个 会不会只登录几个玩家就已经把连接数占完了 其他玩家都访问不了数据库啦？

**Comment by name5566** [comment]
这个是数据库连接数，和玩家数量没关系。不是一个玩家一个数据库连接。

**Comment by jjjjilyf** [comment]
好的 我试试改小一些 谢谢解答，主要是没看懂代码，看到每次都是取得第一个Session，heap也不知怎么用的
![image](https://user-images.githubusercontent.com/7004409/44707521-4c530580-aad7-11e8-9439-da927ece86cb.png)

**Comment by name5566** [comment]
原理就是，如果有 20 个数据库连接，然后有 1000 个用户，这时候会尽量让每个数据库连接服务 50 个用户。

**Comment by jjjjilyf** [comment]
多谢解答

**Comment by 15951836388** [comment]
话说 1个数据库链接，处理多少个用户，比较好？ @name5566

**Comment by name5566** [comment]
可以实际测试决定。
