### ISSUE TITLE
请问Util.map里Get到的元素怎么判断是否为nil

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#119]
用 == nil 来判断，判断不出来，存的是个指针类型的数据。

**Comment by zcwtop** [comment]
if _, ok := m.Get(x); ok {

}

应该这样吧,Get里面也是原始m.m[key]的操作。

**Comment by jjjjilyf** [comment]
@zcwtop 谢谢解答 我试试

**Comment by jjjjilyf** [comment]
@zcwtop  这样是不行的 不过我试了下 用nil来判断就行了，哪怕value是 int类型的，也可以用nil来判断
