### ISSUE TITLE
leaf的console可以接收http消息吗

### ISSUE THREAD

**Issue by Victoryship** [name5566/leaf#130]
可以用console来接收HTTP请求么？可以的话该如何实现？

**Comment by name5566** [comment]
参考：https://github.com/name5566/leaf/issues/39

**Comment by name5566** [comment]
可能额外用 golang 实现一个 web 服务器可行，也可以在 Leaf 内部实现，或者直接使用现有的 Web 服务器，具体还需要想想看。但总体的思路就是，通过 HTTP 把 http 请求转发到 Leaf 的 console 中去。

**Comment by Victoryship** [comment]
嗯嗯，我在想想。谢谢大佬

**Comment by yilinershi** [comment]
@Victoryship 大佬想好了没？最后你是怎么解决的？
