### ISSUE TITLE
leaf查询mgo数据时，有几率报错

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#134]
用leaf的代码，leaf查询mgo数据时，不小的几率报错。有人知道为什么吗？

wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by name5566** [comment]
似乎是 mongo 压力比较大超时了。

**Comment by 15951836388** [comment]
![image](https://user-images.githubusercontent.com/14047483/48474980-b78ab900-e836-11e8-92fc-afe372c6d68b.png)
是这个问题吗

**Comment by name5566** [comment]
这个值是有配置决定的
