### ISSUE TITLE
希望可以增强下log的功能

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#136]
leaf的log蛮好用的了，可以log到文本。但是现在需要做日志分析。要能支持json格式，异步log等等。希望可以加强下。
看了下zap日志库，感觉过去复杂了。有没有简单实用，能分析的日志库？

**Comment by name5566** [comment]
Leaf 的 log 的定位并非用于数据分析，最好额外加一套用于数据分析的机制，同时也保留 Leaf 的 log。

**Comment by 15951836388** [comment]
群主，有什么推荐吗？

**Comment by name5566** [comment]
没有
