### ISSUE TITLE
文档有点少

### ISSUE THREAD

**Issue by liangdas** [name5566/leaf#14]
希望能完善一下文档,多写一些例子

**Comment by name5566** [comment]
打算在 (wiki)[https://github.com/name5566/leaf/wiki] 上加文档。但是不确定什么时候能加上。

**Comment by Think-Jumper** [comment]
我准备用leaf做我的游戏的服务端框架，我想我可以边用边抽空帮你 @name5566 顺便完善下使用文档。

**Comment by name5566** [comment]
非常感谢。可以在 Wiki 提交文档：[https://github.com/name5566/leaf/wiki](https://github.com/name5566/leaf/wiki)

**Comment by Gooooodman** [comment]
看了wiki 还是没安装成功。抱歉我是新手，leafserver]# go install server 在leafserver路径编译没有输出，进去src 编译也是没输出。 go run main.go 报错没有server.json文档讲解有点少。

**Comment by xxy0403** [comment]
@Gooooodman  我也遇到这个问题，不理解“设置 leafserver 目录到 GOPATH 环境变量后获取 Leaf：

”这个怎么设置，一直提示没有server包

**Comment by name5566** [comment]
先阅读：https://golang.org/doc/code.html 一文。

**Comment by liublue66** [comment]
这文档写的你能按你一步一步给搭出来？
