### ISSUE TITLE
Skeleton.AfterFunc 里操作map，导致并发读写 fatal

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#140]
报错 fatal error: concurrent map read and map write

是因为不能用不同的包里的 Skeleton，操作导致的？

因为不能循环引用
我现在是game里的Skeleton调用了别的包里的的逻辑（逻辑里包含自己包里的Skeleton）

这个我要怎么解决？

**Comment by 15951836388** [comment]
似乎要加锁吗？不太想加锁。
还是全部只用1个Skeleton(最低层的那个）？

**Comment by name5566** [comment]
map 不能并发读写，你可以尝试使用 Leaf 自带的 map，或者修改你的代码避免并发读写 map。

**Comment by 15951836388** [comment]
Leaf 提供了一个相同的 AfterFunc 函数，相比之下，f 函数在 AfterFunc 的调用 goroutine 中执行，这样就避免了同步机制的使用：

skeleton.AfterFunc(5 * time.Second, func() {
	// ...
})

看描述，使用AfterFunc ，是不会造成
fatal error: concurrent map writes
fatal error: concurrent map writes

但是，为什么，我却发生了，可能是什么情况导致的？
