### ISSUE TITLE
无法拿到反向代理后的客户端真实IP地址

### ISSUE THREAD

**Issue by karllynnn** [name5566/leaf#141]
目前的RemoteAddr在使用Ngnix做websocket反向代理时，拿到的是Nginx所在机器的ip。正常来讲可以通过nginx新增`X-REAL-IP`之类的header来解决。

不过这里有点尴尬，因为TCP代理和Websocket代理还是有很多不同，按照现在leaf的抽象方式，写一个获取header的方法并不通用，可以思考一下怎么解决这个问题。

**Comment by karllynnn** [comment]
@saplmm 直接改源码当然可以，但是这不符合当前leaf的设计

**Comment by saplmm** [comment]
框架没提供 当然只有自己改....你自己实现一个server 就可以了  这样就符合leaf的设计了，但是 工作量就变大了啊.... 根据业务来吧...几行代码就搞定的事情...别搞复杂了.... 而且修改 也是让你兼容以前，不会造成什么 坏的后果，你还可以pr 让name5566把他合并了...何乐而不为

**Comment by karllynnn** [comment]
我fork了一个repo，将websocket里面的Remote Addr改成返回client的真实地址了，就不提交pr了。`go.mod`里面用`replace`指向自己的就行。
