### ISSUE TITLE
如何清理僵尸连接

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#144]
就是那种，光连接了，然后什么都不做。 连login都不进行，白白消耗服务器的资源。

这种僵尸连接，用什么方案清理比较好？如果要加心跳的话，应该在哪里加，可以检测，踢掉僵尸连接？

**Comment by name5566** [comment]
登录之前可以使用短连接，处理消息以后就立马断开连接。具体还是看你们的需求。

**Comment by chiuan** [comment]
定时器5s不操作强制kill掉agent

**Comment by 15951836388** [comment]
暂时还没用 http做登录。  

@chiuan 请问，在哪里添加这个判断的代码？
