### ISSUE TITLE
skeleton.Go和并发

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#145]
我在leaf的dbchat的例子里看到

用了skeleton.Go，来查询数据库，判断账号是否是新建。

我知道leaf除了消息接受那块是多携程。具体逻辑数据都是在一个携程里，没有并发的问题。

但是，用了skeleton.Go，还会不会有并发问题？（逻辑数据处理和读写数据库）

**Comment by 15951836388** [comment]
这里 用 Insert ，全局唯一key，可以保证了不会被重复插入。
但是用 Upsert和update就不行了，可能会出现覆盖的情况

**Comment by name5566** [comment]
MongoDB 有原子操作。你需要保证 Go 中的代码能支持并发执行
