### ISSUE TITLE
skeleton.Go和user.Go

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#147]
在leaf的server_db_example例子里

login里，用的是skeleton.Go

logout里，用的是user.Go

可以说说在用的时候的区别吗？

**Comment by name5566** [comment]
user.Go 能够保证执行的顺序

**Comment by 15951836388** [comment]
看文档里的 描述 skeleton.Go传入的2个方法，也是顺序的啊？

**Comment by name5566** [comment]
你可以看一下 Leaf 的 Go 的例子：
https://github.com/name5566/leaf/blob/master/go/example_test.go

ExampleLinearContext 展示了执行顺序的含义。
