### ISSUE TITLE
敲击 Ctrl + C 关闭游戏服务器？

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#148]
不太明白，部署到云服务器后，这个集体是怎么操作的？可以详细说说嘛

“敲击 Ctrl + C 关闭游戏服务器”

**Comment by name5566** [comment]
kill -2 也可以

**Comment by 15951836388** [comment]
@name5566 那在dcoker里，如何实现这个 "kill -2"?

**Comment by 15951836388** [comment]
@name5566 那在dcoker里，如何实现这个 "kill -2"?

**Comment by name5566** [comment]
docker stop
docker kill

文档看一下吧，这个问题应该不难吧
