### ISSUE TITLE
skeleton.Go 可以返回值吗？

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#149]
leaf 的 db例子里，用skeleton.Go 读取数据库。

具体的逻辑代码都是在d.Skeleton.Go里的，不够通用

但是 d.Skeleton.Go里没有返回值。不知怎么修改代码，才能正确实现这个功能

现在想封装一下，类似下面这样。
![image](https://user-images.githubusercontent.com/14047483/53214407-700e9700-3687-11e9-9b5e-e58c33b31db9.png)

**Comment by 15951836388** [comment]
比如客户端，查看帮派成员列表，但是列表里很多人不在线，这时需要批量从数据库里读取出角色数据。然后下发客户端。
这里，就比较需要上面的封装了。

**Comment by name5566** [comment]
大概这样：
`var ret
skeleton.Go(func() {
    // 执行操作
    ret = 结果
}, func() {
    // 处理结果 ret
})`

**Comment by 15951836388** [comment]
我知道可以这样，凡是需要读取离线玩家数据的，都要写skeleton.Go。

不能封装成返回值吗？

**Comment by 15951836388** [comment]
很多功能，写起来，都不太方便

**Comment by name5566** [comment]
skeleton.Go 和官方的 go 是一样的。否则就是需要阻塞等待了。
