### ISSUE TITLE
如何组织文件

### ISSUE THREAD

**Issue by sundream** [name5566/leaf#150]
假定我游戏逻辑均放到server/game/internal中,游戏中存在玩法1，玩法2，玩家相关模块，这些模块都要用到internal.skeleton,大致结构如下
```
+server
 +game
   +internal
     +playunit1   玩法1
     +playunit2   玩法2
     +player       玩家模块
     +module.go      //在module模块我会初始化游戏全局变量,如玩家管理器，活动管理器等
     +handler.go
```
现在问题是: 如果我按玩法分文件夹后,就需要导入"server/game/internal",而server/game/internal/module.go#OnInit()中又需要导入各个玩法包,这样存在相互引用。本人刚接触leaf，对go也不是很熟，请问有什么好的方式组织文件。
我目前想到解决上面问题的方法是不分文件夹，所有业务代码都和server/game/internal/module.go处于同一级,并且都在internal包下，感觉这种方式比较low，如下
```
+server
  +game
    +internal
       +playunit1_A.go
       +playunit1_B.go
       +playunit2_A.go
       +playunit2_B.go
       +module.go
       +handler.go
```

**Comment by karllynnn** [comment]
你这些玩法之间没有共同的接口么？抽象一个interface定义在外部，在internal里面放一个package `play`，把玩法放里面，通过interface不就解耦了么。

你把这个东西放在leaf的issue里面不合适，去提问网站问。
