### ISSUE TITLE
leaf用于非游戏类服务的可行性？

### ISSUE THREAD

**Issue by StaticGameStudio** [name5566/leaf#151]
现在游戏内需求一个类似于百度贴吧，有一些即时互动功能的留言板。不知道能不能就用leaf来做呢？还是去找一个Gin一类的http框架来做？个人感觉用leaf似乎完全可行。不知道有没有什么需要注意的地方呢？求指教，谢谢~

**Comment by karllynnn** [comment]
如果你需要请求-应答模型，leaf现在封装的websocket/tcp都不支持，你需要自己封装RPC协议。

**Comment by StaticGameStudio** [comment]
> 如果你需要请求-应答模型，leaf现在封装的websocket/tcp都不支持，你需要自己封装RPC协议。

已经决定就用leaf的websocket来做了，感谢解答
