### ISSUE TITLE
为啥不能在leaf　目录下运行ｇｏ ｂｕｉｌｄ 生成package ?

### ISSUE THREAD

**Issue by oxpy** [name5566/leaf#152]
为啥不能在leaf　目录下运行ｇｏ ｂｕｉｌｄ 生成package ?

**Comment by karllynnn** [comment]
leaf只是一个库，又没有main文件，你要build啥。还有你能不能把输入法换成半角，看着不别扭么…

**Comment by googege** [comment]
你可以在你的任意目录新建一个目录，然后 `go mod init`初始化后 新建一个 main.go main包的test文件，然后引入本项目的测试示例然后build 。
