### ISSUE TITLE
leaf的压力测试

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#153]
请问，leaf的游戏机器人压力测试，有什么推荐方案？
看代码里的WSClient 似乎可以用来做压力测试，尝试了下，感觉不太适用。（机器人的逻辑在哪里处理？）
作者可以出个简单范例吗？或者大致说下思路

**Comment by 15951836388** [comment]
机器人逻辑，似乎可以通过WSClient.NewAgent 传进来。

**Comment by name5566** [comment]
是的，可以使用 wsclient
