### ISSUE TITLE
leaf  引入 服务器渲染的设想

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#159]
比如想看看某个地图里的玩家位置分布

想在leaf里，调用1个go语言的ui库，然后简单绘制出来

leaf里的数据，怎么传给ui库，不断的绘制出来

一般的ui都是直接霸占了主线程，不太好和leaf结合

希望作者给个合适方案哈

**Comment by name5566** [comment]
只能放在其他 goroutine 执行了

**Comment by 15951836388** [comment]
问题是怎么获得leaf的数据？

**Comment by name5566** [comment]
类似数据库的做法是否可以？

**Comment by 15951836388** [comment]
难道gui用 chanrpc，往外取leaf的数据？

**Comment by name5566** [comment]
或者把它放在单独一个模块中，供其他模块调用

**Comment by 15951836388** [comment]
应该不行，gui一般都是一个死携程一直跑的，感觉只能通过数据传输

**Comment by name5566** [comment]
那只能自己按需求实现了
