### ISSUE TITLE
deeclone的调用

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#160]
![image](https://user-images.githubusercontent.com/14047483/60851429-b541f880-a225-11e9-9f34-27e4be8883cd.png)

1、这里deeclone放在了user.go的外面，是有什么有意吗？
放到user.go里面了，好像也没什么影响。

2、这里的的user.go，能不能换成skeleton.Go？

3、如果不能换的话，所有的user能不能共用1个*g.LinearContext？感觉每个user都创建*g.LinearContext，有点浪费

**Comment by name5566** [comment]
1. 因为是两个不同的 goroutine
2. user.Go 能够保证 goroutine 的执行顺序
3. 这种消耗不用考虑，意义不大

**Comment by 15951836388** [comment]
1.如果deeclone放到user.go里面会引发什么样的问题？因为并没有改变userdata的数据，应该不会有问题吧？

**Comment by name5566** [comment]
很难保证这一点。
