### ISSUE TITLE
关于扩容的问题

### ISSUE THREAD

**Issue by qiangv** [name5566/leaf#161]
原先是做端游，初入H5游戏开发，发现了这个仓库，很棒！
游戏框架的逻辑我学习了下，有个疑问，当出现负载问题的时候，如何进行动态扩容呢？
我的设想是做一系列的H5游戏，一个游戏启动一个docker，N个游戏N个docker，有一个网关负责分配用户到特定的游戏docker里，当不足的时候进行扩容，然后有一个GM端可以进行管理，但总觉得怪怪的，不知道这个你有什么指导的么？

**Comment by 15951836388** [comment]
leaf是单服框架，不是分布式。你的需求需要把leaf改成分布式，或者用别的分布式框架

**Comment by qiangv** [comment]
好的。谢谢。
