### ISSUE TITLE
leaf的发展规划

### ISSUE THREAD

**Issue by shen3335600** [name5566/leaf#164]
请问作者设计leaf的目标是什么
在未来是否可能会支持分布式
最近的迭代计划是什么呢

**Comment by name5566** [comment]
暂时不支持分布式。现在以修改 bug 为主（如果有）。

**Comment by shen3335600** [comment]
请问作者设计leaf的初衷是什么呢，比如mqant就以实现微服务为目标。
leaf主要用来服务于什么类型的项目呢？
未来是否会考虑分布式？

**Comment by name5566** [comment]
Leaf 是一个通用的游戏服务器框架。
