### ISSUE TITLE
请问怎样进行心跳包检测? 

### ISSUE THREAD

**Issue by a997093108** [name5566/leaf#166]
在抓包分析别的游戏都是由服务端发消息给客户端,用于心跳检测. 
但Leaf中没有关于WriteMsg()函数发送消息失败的信息. 那么该怎样办啊?

求大神解答鸭!!!

**Comment by name5566** [comment]
心跳检测和 WriteMsg 是否返回失败没有关系。心跳检测可以根据游戏具体需要在逻辑层实现。

**Comment by a997093108** [comment]
已在Leaf QQ群获取到答案.
大概描述是,客户端或者服务器定时发包,检测超时时间判断心跳.
谢答!
