### ISSUE TITLE
写个框架深度源码剖析

### ISSUE THREAD

**Issue by tiancityycf** [name5566/leaf#17]
写个框架深度源码剖析 就更好了  对于新手学习  谢谢楼主 谢谢大神

**Comment by name5566** [comment]
目前来说，提出具体的问题，然后针对具体问题解答，最后归类成文档，这种方式可以尝试。

**Comment by Think-Jumper** [comment]
@name5566 我现在就遇到了关于leaf在protobuf解析器解析接受到的消息的问题，请你指点下：在leaf/network/protobuf/protobuf.go下的代码里面的函数：Unmarshal，我不太明白你的意图，包括注册那里，能讲解下吗？

**Comment by name5566** [comment]
Unmarshal 用于将二进制数据转换为一个具体的消息。更多内容可以留意 wiki：[https://github.com/name5566/leaf/wiki](https://github.com/name5566/leaf/wiki)
