### ISSUE TITLE
QQ群现在设置不能加入吗

### ISSUE THREAD

**Issue by wuhuiheu** [name5566/leaf#170]

**Comment by a997093108** [comment]
大概是人满了...
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"wuhuiheu"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年11月26日(星期二) 下午4:33
 收件人:&nbsp;"name5566/leaf"<leaf@noreply.github.com&gt;;
 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
 主题:&nbsp;[name5566/leaf] QQ群现在设置不能加入吗 (#170)

**Comment by name5566** [comment]
QQ 群现在是付费入群。
