### ISSUE TITLE
chan的buff数量设置

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#171]
![image](https://user-images.githubusercontent.com/14047483/69687781-16983480-10ff-11ea-8c94-e49a943d5a28.png)
leaf的chan的buff数量设置，默认都是10000，会浪费内存的吧
由于没办法确定，真正的线上压力，不知道 buff数量设置多少合适

有大概的参考数字吗？或者一般根据什么来设置这个数量

**Comment by nxlsBoy** [comment]
压测就好啦； 写机器人，然后模拟可能的压力情况；然后看看服务器状态，然后再设置这个值

**Comment by 15951836388** [comment]
具体点啊，怎么判断chan的数量够不够

**Comment by nxlsBoy** [comment]
1. 压测，模拟请求，发送大量的请求给服务器
2. 然后实时检测chan的数量，取一个平均值即可吧

**Comment by name5566** [comment]
可以看一下源码，占用内存很少的。每个 len 都有其特定含义。只有在一些非常极端的情况下出现数量不够（通常来说不太可能出现），一般来说是服务器本身存在 bug。
