### ISSUE TITLE
关于解析器

### ISSUE THREAD

**Issue by ziwindly** [name5566/leaf#18]
解析器没有提供一个统一的littleEndian 会造成发送流 和 接收流 编码不一致
你的demo 中指涉及到json的数据格式 如果是二进制的数据格式 就很容易造成问题 
也许是因为我对这个框架的认知度不够高 有些设计思想上可能没有明白过来

**Comment by name5566** [comment]
endianess 是可以配置的。参考：https://github.com/name5566/leafserver/blob/master/src/server/conf/conf.go 中的 `LittleEndian` 配置项。

**Comment by ziwindly** [comment]
不是你那块的配置地方 你那块只是对路由收包做了设置 发包如果是二进制 protobuf.go 中 SetByteOrder 没有地方调用 导致解析器 如果编码成二进制流的时候  消息号那块 会出问题 不知道是不是我的理解错误

**Comment by name5566** [comment]
protobuf 本身自己会处理
