### ISSUE TITLE
leaf关闭时的清理问题

### ISSUE THREAD

**Issue by 15951836388** [name5566/leaf#181]
leaf关闭时

1.Skeleton里的dispatcher，没有关闭ChanTimer

2.db范例里，user的 logout里，也没有关闭 g.LinearContext

这些事应该关闭的吧？如果不关闭的话，会有什么影响吗？

**Comment by name5566** [comment]
leaf 已经处理好了。有一些是需要等待关闭，有一些不能也不需要等待。
