### ISSUE TITLE
如何提高前后端数据传输的安全性呢?

### ISSUE THREAD

**Issue by JamesBobo** [name5566/leaf#184]
有没有一个好的方式去对前后端消息进行加解密处理 现在看来如果直接明文传输的话多少有些不太安全

**Comment by name5566** [comment]
加密是可以的。不过，安全不仅仅是加密的问题，而是一整套的算法和流程，这是一个相对复杂的问题。

**Comment by JamesBobo** [comment]
如果说要单纯实现消息加密 那么只能通过改动leaf代码实现了吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 中午11:12
收件人: ***@***.***&gt;; 
抄送: "ルパン  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [name5566/leaf] 如何提高前后端数据传输的安全性呢? (#184)





 
加密是可以的。不过，安全不仅仅是加密的问题，而是一整套的算法和流程，这是一个相对复杂的问题。

**Comment by name5566** [comment]
增加消息加密不需要修改 leaf 代码的。根据你们具体需求，考虑 leaf 提供的接口或者其他方案。

**Comment by JamesBobo** [comment]
如果前端发送的消息是加密的&nbsp; leaf如何确定这条消息交给那个模块取处理呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月1日(星期四) 中午11:29
收件人: ***@***.***&gt;; 
抄送: "ルパン  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [name5566/leaf] 如何提高前后端数据传输的安全性呢? (#184)





 
增加消息加密不需要修改 leaf 代码的。根据你们具体需求，考虑 leaf 提供的接口或者其他方案。
