### ISSUE TITLE
群主的群还是要注意一下

### ISSUE THREAD

**Issue by kolonse** [name5566/leaf#20]
在你们群里呆了一段时间,本来是想看看有什么好的建议及思想我能吸取下,有什么见解也能听到,但是没想到好多都是带着程序员高傲光环说话,人家反馈了一个现实结果群里就一堆类似小学生的吐槽,建议清理下,本人已经退群！这个东西和pomelo还是挺类似的,pomelo的群非常好,对于同一个问题的反馈有完全不同的反响！你的这个群里面最好也能管理完善一下,不太建议为了人气什么人都加！

**Comment by Think-Jumper** [comment]
老兄，你这么快就来这里反映了，看来我刚刚的辛苦没白费。

**Comment by Think-Jumper** [comment]
@kolonse 我刚刚还想着我把我在这里说过的话和相关承诺删掉，当自己没来过，但是看到你这句，我删一般就停了
