### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by dutok** [name5566/leaf#22]
Hi. I'm trying to implement authentication into my game server with a username and password. What is the best practice for doing this in Leaf?

(I'm sorry if this is the wrong place to ask. I'm just kinda stuck with doing this in my application.)

**Comment by name5566** [comment]
Hi, dutok. In [Leafserver](https://github.com/name5566/leafserver), You can place the auth code in [Login module](https://github.com/name5566/leafserver/tree/master/src/server/login) and than notifies Game module by its ChanRPC: https://github.com/name5566/leafserver/blob/master/src/server/game/external.go
