### ISSUE TITLE
在 Leaf 中使用 Protobuf，客户端如何对接服务器

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#26]
Wiki文档中并没有提供相关代码，只好硬着头皮自己写

	conn, err := net.Dial("tcp", "127.0.0.1:3563")
	if err != nil {
		panic(err)
	}

	hello := &msg.Hello{
		Name: proto.String("leaf"),
	}

	data, err := proto.Marshal(hello)
	if err != nil {
		log.Fatal("marshaling error: ", err)
	}

	// len + data
	m := make([]byte, 2+len(data))

	// 默认使用大端序
	binary.BigEndian.PutUint16(m, uint16(len(data)))

	copy(m[2:], data)

	// 发送消息
	conn.Write(m)

服务端打印：
2016/12/16 21:04:35 [debug  ] unmarshal message error: message id 2564 not registered

不知道该怎么办了

**Comment by name5566** [comment]
在网络中传输的消息格式如下：
-------------------------------
| len | id | protobuf message |
-------------------------------
其中len默认为两个字节，len和id默认使用网络字节序。

上面的代码，你没有消息 id，建议你直接使用 leaf 的 protobuf processor（https://github.com/name5566/leaf/blob/master/network/protobuf/protobuf.go），或者参考相关代码。

**Comment by heyuanchao** [comment]
谢谢作者的指点，问题已经解决，现在分享出来，有写的不好的地方请指正

	conn, err := net.Dial("tcp", "127.0.0.1:3563")
	if err != nil {
		panic(err)
	}

	var Processor = protobuf.NewProcessor()
	Processor.Register(&msg.Hello{})

	data, err := Processor.Marshal(&msg.Hello{
		Name: proto.String("leaf"),
	})
	if err != nil {
		log.Fatal("marshaling error: ", err)
	}

	// len + id + data
	m := make([]byte, 4 + len(data[1]))

	// 默认使用大端序
	binary.BigEndian.PutUint16(m, uint16(2 + len(data[1])))

	copy(m[2:], data[0])
	copy(m[4:], data[1])

	// 发送消息
	conn.Write(m)

	buf := make([]byte, 32)
	n, err := conn.Read(buf)
	if err != nil {
		log.Fatal("read error:", err)
	}

	recv := &msg.Hello{}
	err = proto.Unmarshal(buf[4:n], recv)
	if err != nil {
		log.Fatal("unmarshaling error: ", err)
	}

	fmt.Println(recv.GetName())

**Comment by chiuan** [comment]
来写一个sproto的吧！

**Comment by name5566** [comment]
支持 sproto 只需要按 protobuf 或者 json 的做法，实现 Processor 接口（[https://github.com/name5566/leaf/blob/master/network/processor.go](https://github.com/name5566/leaf/blob/master/network/processor.go)）即可。

**Comment by chiuan** [comment]
客户端如何正确处理消息 ID？

由于消息 ID 是服务器生成的，因此建议服务器导出消息 ID 给客户端使用。这里提供一个简单的思路，假定客户端使用 Lua，这时候服务器可以导出消息 ID 为一个 Lua 源文件，此源文件中包含一个 table，可能内容如下：

msg = {
    [0] = "msg.MsgA",
    [1] = "msg.MsgB",
    [2] = "msg.MsgC",
}
Lua 客户端加载此 Lua 源文件，得到 msg table，然后就可以从消息 ID（网络中过来的消息）

@name5566 
这里提及到服务器下发这些id对应消息名称，那么想问下：
1、是服务器启动时候生成这样一个table存起来，然后每个客户端登陆就发
2、假如利用protobuf进行生成协议文件时候，顺带把这个序号的table文件生成存到客户端
你觉得2种哪种更好？

**Comment by name5566** [comment]
这里说的方式是：导出消息 ID 为一个 Lua 源文件，此源文件中包含一个 table。也就是说，可以编写一个额外的导出程序，在诸如编译服务器的时候执行，这个导出程序导出 Lua 源文件，这个 Lua 源文件直接被客户端使用。在协作中，可以把 Lua 源文件提交到 SVN，客户端更新得到最新的消息 ID。

**Comment by chiuan** [comment]
明白，我也是觉得应该这样。以前pomelo有客户端连接时候是服务器下发的协议文件。

**Comment by chiuan** [comment]
@name5566 经过实战，一直想改掉Processor的Register方法，可以传一个自定义协议序号，这样比较好的做到向下兼容吧，保持老协议的序号一致。

**Comment by name5566** [comment]
如果需要，可以按需求调整一下，重新实现一个 Processor，替换掉默认的。
