### ISSUE TITLE
定时器的功能太少，能否适当跟进增加功能？

### ISSUE THREAD

**Issue by Think-Jumper** [name5566/leaf#28]
首先感谢作者的开源精神！个人在使用leaf过程中提交点小建议。
感觉目前的定时器功能还不够，有个常见的需求不具备，说明如下：
根据指定定时器名称，可设置时间间隔，定时轮训执行某个func()，以此创建定时器触发器。
并提供相关的查询、修改时间间隔、停止、清理等相关接口。
需要注意的是，需要从整体去规划定时器的触发，而不是任意创建一个定时器就等待它自己内部按自己内部的时间触发。例如，创建一个房间，房间会按每秒50次触发房间广播的定时轮询触发器A，如果有100个房间总不能100个定时器吧？应该是100个房间都在定时轮询触发器A内触发吧。
个人拙见，见效勿怪。

**Comment by chiuan** [comment]
你这个貌似跟定时器本身设计没关系吧。
都是逻辑设计组合问题。你要一个定时器管理你100个房间的刷新不就行了？

**Comment by Think-Jumper** [comment]
@chiuan 按你的logic，作者里面设计了计划定时器，其实我自己也可以自己实现、自己管理，甚至于leaf里面本身的timer里面的东西都不是必要的，那为啥作者还要加进去？

**Comment by chiuan** [comment]
不是。我看leaf的定时器不也够用了么？

**Comment by name5566** [comment]
Leaf 提供了定时器的[创建](https://github.com/name5566/leaf/blob/master/timer/timer.go#L51)和[停止](https://github.com/name5566/leaf/blob/master/timer/timer.go#L27)接口。

按时间间隔执行某个函数：

```
func wrapper() {
	// 以 d 作为时间间隔
	// 可以通过修改 d 的值来改变下一次执行的时间间隔
	//
	// 通过 timer 变量可以停止定时器的执行
	timer := skeleton.AfterFunc(d, func() {
		wrapper()

		// 具体执行内容
		...
	})
}
```

另外，根据具体的逻辑，可以基于基础的功能做适合自己的扩展。需要提示的就是，定时器在触发的时候，会存在一个额外的 goroutine 创建的开销。

**Comment by name5566** [comment]
在某些场合，需要按固定（或者说某种）频率来做更新操作，这时候性能最佳的方案可能是定义自己的 skeleton，在 select 的 default 中实现相关功能。

**Comment by Think-Jumper** [comment]
@name5566 好的，收到！谢谢作者。另外我还有个疑问，之前你有个跟Leaf Framework与之搭配作为应用范例的LeafServer，为何现在把里面的一些用例（注册消息触发对应的事件）给清空，变成个空壳子了呢？这样岂不是变成很多地方使用实际上就不知道要怎么用了？有什么用意吗？因为我有个疑惑:Login Module里面的代码和Game Module实际上是重复的，但是在这里：[https://github.com/name5566/leaf/issues/22](url)讨论的时候，好像是别有用意，我感觉我是不是把很多地方的误用了？（即使我现在已经把我的游戏服务端写好在运行了。）

**Comment by name5566** [comment]
Leaf server 是一个空壳（没有清空过代码），需要按照具体场合来填充代码到 Leaf server 中去。Login Module 主要用于处理和登录服务器（或者第三方帐号系统）的交互。

**Comment by Think-Jumper** [comment]
@name5566 好的，谢谢解疑。

**Comment by alex023** [comment]
@Think-Jumper ,定时器要支持复杂的业务，就自己封装。可参考github的代码，基于一个timer实现的定时及事件提醒的定时器：
[https://github.com/alex023/clock](url)
