### ISSUE TITLE
在 Leaf 中如何操作 MongoDB 数据库

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#29]
我想实现用户登录的功能，然后将用户信息记录到数据库中，该如何实现，相关的介绍有点少

**Comment by name5566** [comment]
Leaf 提供了基础的 MongoDB 的操作接口。其他需要按具体的游戏情况自己设计了。

**Comment by heyuanchao** [comment]
谢谢作者，已经在Go游戏服务器交流QQ群 376389675 找到数据库操作相关示例代码

![image](https://cloud.githubusercontent.com/assets/10580354/21835519/9463fd2e-d7f8-11e6-951b-120e76fe666d.png)
