### ISSUE TITLE
Documentation, what does leaf do?

### ISSUE THREAD

**Issue by endel** [name5566/leaf#3]
I've seen this project at [awesome-go](https://github.com/avelino/awesome-go#game-development). Unfortunately it's description doesn't help much about describing itself and it's features.

Does It handle web-sockets? It stores users data? It has an REST API? 

I would love to contribute in some way.

Thank you

**Comment by adamcharnock** [comment]
:+1:

**Comment by name5566** [comment]
Leaf v1.0 does not support WebSocket, it will supports in a future version. MongoDB is used to store data. English documents have not written, the best way to understand the code is to read the code.
