### ISSUE TITLE
请教个问题，多个请求时候如何保证同个模块数据一致

### ISSUE THREAD

**Issue by hujunlong** [name5566/leaf#30]
例如：自己写了个战斗模块进行计算，多个玩家同时请求是否会出现并发问题？

**Comment by name5566** [comment]
如果所有玩家数据都在一个模块中，不存在问题。多个模块间通过 ChanRPC 通讯，也不存在类似问题。模块之间不能直接访问对方数据。不建议使用过多的模块。

**Comment by hujunlong** [comment]
谢谢
