### ISSUE TITLE
是否有必要控制台提供agent 模块 状态查询

### ISSUE THREAD

**Issue by hujunlong** [name5566/leaf#31]
比如一个模块挂掉了，是否有必要通过控制台在把服务启动起来！以及 模块中是否有线程死锁，如何让底层暴露信息出来？

**Comment by name5566** [comment]
1. 模块目前不太可能会挂掉
2. 每个模块跑在单独的 goroutine 中，使用 Leaf 提供的机制不太需要考虑死锁的问题

**Comment by hujunlong** [comment]
谢谢
