### ISSUE TITLE
在 Leaf 中如何获取客户端的ip地址

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#32]
客户端向Leaf发送消息，Leaf如何获得客户端的ip地址？

**Comment by name5566** [comment]
RemoteAddr()，详见：https://github.com/name5566/leaf/blob/master/network/conn.go#L11

**Comment by heyuanchao** [comment]
func handleHello(args []interface{}) {
	// 收到的 Hello 消息
	m := args[0].(*msg.Hello)
	// 消息的发送者
	a := args[1].(gate.Agent)

	// 输出收到的消息的内容
	log.Debug("hello %v", m.Name)

	// 给发送者回应一个 Hello 消息
	a.WriteMsg(&msg.Hello{
		Name: "client",
	})
}

在这里如何取得RemoteAddr()呢？

**Comment by name5566** [comment]
我修改了下，在 agent 中增加了相关接口：https://github.com/name5566/leaf/commit/2c74d131ce8b1d3682a8bdf615cd15bc97acdf65#diff-ddfe83a4e9221ae35e08ccea531d3711
