### ISSUE TITLE
msgInfo 命名混淆

### ISSUE THREAD

**Issue by zcrayccy** [name5566/leaf#34]
type Processor struct {
	msgInfo map[string]*MsgInfo
}

type MsgInfo struct {
	msgType       reflect.Type
	msgRouter     *chanrpc.Server
	msgHandler    MsgHandler
	msgRawHandler MsgHandler
}
这两个msgInfo 是通过大小写来区分的，容易混淆，上面msgInfo 改成 msgMap 之类比较好。

**Comment by name5566** [comment]
问题不大：）

**Comment by Mikejinhua** [comment]
大小写区分类和对象是常用的啊
