### ISSUE TITLE
在 Leaf 中如何检测网络异常的客户端已经断开连接

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#37]
当使用WebSocket进行通讯时，手动关闭客户端，服务端能够监听到客户端关闭。如何客户端突然网络异常，比如手动关闭网络连接，服务端将收不到客户端的任何请求，这种情况下服务端要如何处理才能知道客户端已经断开连接？

**Comment by name5566** [comment]
通过心跳包来检查。

**Comment by heyuanchao** [comment]
@name5566 心跳包设置成多久发一次比较好，看网上有说30-40秒发一次，一次检测不到就认为断线，还有说6-9秒发一次，三次检测不到就认为断线

**Comment by name5566** [comment]
按项目实际情况来看吧。
