### ISSUE TITLE
在 Leaf 中如何与HTTP服务器通讯

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#39]
比如我要接入微信支付、支付宝，要访问一些http/https的接口，是直接用Go提供的net/http包吗？

**Comment by name5566** [comment]
可以使用 Go 的 net/http 包并使用 ChanRPC 进行通讯。

**Comment by fireice009** [comment]
@name5566 
http.ListenAndServe 能否放在Module 里面执行？发现这样会阻塞后续的流程。还是说要用 skeleton.Go 来执行？或者在 main.go 里面执行，不加到 Module 里？

**Comment by name5566** [comment]
独立启动一个 goroutine 进行 ListenAndServe，不要用 skeleton.Go 来创建这个独立的 goroutine

**Comment by chiuan** [comment]
可以出一个http_network

**Comment by heyuanchao** [comment]
@name5566 现在需要使用 Leaf 做一个管理后台，在 game 模块的什么地方启动 一个独立的 goroutine 进行 http.ListenAndServe  才比较好？

**Comment by 15951836388** [comment]
不知道用发送http给leaf的conslo，来实现gm行不行？
https://github.com/name5566/leaf/wiki/Leaf-console
