### ISSUE TITLE
Lock granularity in TCPConn

### ISSUE THREAD

**Issue by ichenq** [name5566/leaf#4]
mutex只为同步一个closeFlag变量，更改为atomic是否会好一点？

defer is function scope, maybe sync.atomic is better for sync.Mutex?

**Comment by name5566** [comment]
关于使用一个变量来充当锁的问题，这是一个需要考虑的问题。细究的话，这是一个略微复杂的问题，你可以看看：http://name5566.com/4535.html 一文。回到 Golang，我还没太研究过其内存模型，不过我找到此文：https://golang.org/ref/mem。有空我再去研究研究。这里用 Mutex 是一种保险的做法，无论何种情况下一定不会出错（乱序的问题）。再就是，这里应该不太会引起性能问题。我会在后面的版本来做一个整体的优化。

**Comment by name5566** [comment]
这里的 mutex 不仅仅是用于同步 closeFlag 变量。它保证了对同一个连接，Destroy()、Close()、Write() 串行执行。想象一下：

* 在不同 goroutine 中同时执行 Destroy 和 Close 的情况
* 在不同 goroutine 中同时执行 Destroy 和 Write 的情况

使用 mutex 以后，逻辑更加清晰简单。如果存在性能问题，之后可以再做优化。
