### ISSUE TITLE
客户端Unity，通信协议WebSocket，如何解析Leaf消息

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#45]
在 https://github.com/name5566/leaf/issues/19 中讲到，服务器回应的是二进制数据，那么在Unity中如何解析二进制数据，目前用的是BestHttp

**Comment by heyuanchao** [comment]
Encoding.UTF8.GetString(e.data)

**Comment by nlmayday** [comment]
在框架中不能直接返回 json字符串吗，在js中解析二进制感觉有些麻烦啊

**Comment by name5566** [comment]
@nlmayday 目前是不允许的，主要是为了和 TCP 协议兼容。
