### ISSUE TITLE
用go自带的testing做单元测试，报错：conf/server.json No such file or directory.

### ISSUE THREAD

**Issue by fireice009** [name5566/leaf#46]
在 server/game/internal/ 目录下，创建与game.go 同级目录的 game_test.go，运行 go test 报错。
在server/game/internal/ 目录下创建 ./conf/server.json 能解决问题。但显然是不合理的做法。
求解。

**Comment by name5566** [comment]
可以参考下 Leaf 里面的 test 用法。

**Comment by fireice009** [comment]
leaf 和 leafserver 都没找到例子。现在通过手动加载配置文件解决了。

**Comment by jjjjilyf** [comment]
请问下 具体指的是哪个test啊？全局查找了关键字 XX_test.go文件里用到 conf关键字的 只有 
```
package main

import (
	"fmt"
	"server/conf"
	"server/mysql"

	"github.com/name5566/leaf"
	lconf "github.com/name5566/leaf/conf"
)

type Account struct {
	PlayerID  uint   "gorm:primary_key"
	AccountID string `gorm:"not null;unique"`
	Password  string
}

```

但是并没有实际的用法啊。。。
