### ISSUE TITLE
mongodb auth 问题

### ISSUE THREAD

**Issue by fireice009** [name5566/leaf#47]
gopkg.in/mgo.v2 的 mgo.Session 被封装起来了，而 Login 接口没有开放出来。
该怎么做 auth 呢？

**Comment by name5566** [comment]
方法有多种，具体看一下 mgo 的文档。另外 mgo session 是暴露出来的，可以直接使用：https://github.com/name5566/leaf/blob/master/db/mongodb/mongodb.go#L13。
