### ISSUE TITLE
怎样正确关闭 gate.Agent?

### ISSUE THREAD

**Issue by fireice009** [name5566/leaf#48]
分别调用 Agent.Close()， Agent.Destroy()，或者一起调用，都会有日志：
`[debug  ] read message: read tcp 127.0.0.1:9999->127.0.0.1:60990: use of closed network connection`

**Comment by name5566** [comment]
1. 使用 Close 还是 Destroy 可以看：https://github.com/name5566/leaf/issues/13
2. 日志的具体内容和 Go 语言版本有关，见文档：https://github.com/name5566/leaf/blob/master/TUTORIAL_ZH.md
