### ISSUE TITLE
"read message error: EOF" printed when run sample

### ISSUE THREAD

**Issue by meiosischen** [name5566/leaf#5]
| => ./server
2015/09/24 19:25:00 [release] Leaf starting up

2015/09/24 19:25:05 [debug  ] read message error: EOF
2015/09/24 19:25:05 [debug  ] hello leaf

看了几个golang game server后我觉得leaf最有条理性。首先感谢分享。
我在使用你的leaf server示例代码时，发现每次收包会有 EOF错误（但不影响主逻辑）
我对golang不熟，利用各种方法（包括gdb）弄了半天没搞清楚是哪里错了，原先以为是客户端write后没有close connection，但是close了还是报错，只能麻烦你帮忙解答下了，谢谢。

**Comment by name5566** [comment]
Leaf 会在客户端网络断开的时候输出断开的原因，这里只是一个提示并不表示服务器内部发生了错误。错误日志总是以 [error] 开始，这里为 debug 日志。

**Comment by name5566** [comment]
修改了一下文档和日志输出，这样就不容易产生误解了。

**Comment by jmesyan** [comment]
![image](https://user-images.githubusercontent.com/21181503/37555390-6fcc5f48-2a21-11e8-9e20-81b55aec23a3.png)
为什么我只会输出错误

**Comment by Balzac1799** [comment]
@jmesyan 需要重新`go install server`

**Comment by jmesyan** [comment]
我知道了，消息没配对@ Balzac1799
