### ISSUE TITLE
消息结构体如何添加其他结构体？

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#50]
在msg/msg.go中，

const (
	S2C_Auth_OK           = 0
	S2C_Auth_AccIDInvalid = 1
)

type S2C_Auth struct {
	Err int
}

在game/internal/userdata.go中，

type UserData struct {
	UserID int "_id"
	AccID  string
}

想让S2C_Auth添加UserData，

type S2C_Auth struct {
	Err int
        Data UserData
}

该如何处理，还是说消息结构体中只能是string、int、bool、[]string、[]int基本数据类型？

**Comment by name5566** [comment]
JSON 支持数据类型均可。结构体可以嵌套。

**Comment by heyuanchao** [comment]
@name5566 但是我这么写的时候，IDE会找不到UserData这个结构体，手动写import "server/game/internal/userdata"也不行
