### ISSUE TITLE
Unity建立socket，怎么发送能被leaf解析的json数据呢

### ISSUE THREAD

**Issue by TinchyChing** [name5566/leaf#54]
我一直没有搞懂怎么在unity发送能够被leaf服务端解析的数据，是直接发送json格式的过去吗？
![image](https://user-images.githubusercontent.com/13182485/28753484-6304abe0-7567-11e7-9c17-7d1e7de67d49.png)

**Comment by name5566** [comment]
参考文档中 Golang 实现的客户端。
