### ISSUE TITLE
在 Leaf 中如何更好地实现权限管理？

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#55]
实现权限管理有什么比较好的方式

**Comment by name5566** [comment]
具体来说是？

**Comment by heyuanchao** [comment]
目前需要做一个Web游戏管理后台，比如管理员登录、用户管理、安卓客户端版本管理，又不想完全用WebSocket 协议，在 game 模块的什么地方启动 一个独立的 goroutine 进行 http.ListenAndServe 才比较好？

**Comment by name5566** [comment]
可以使用 Go 的 net/http 包并使用 ChanRPC 进行通讯。独立启动一个 goroutine 进行 ListenAndServe，不要用 skeleton.Go 来创建这个独立的 goroutine。这两个点需要注意一下。
