### ISSUE TITLE
两个不同的 LeafServer 之间如何更好的实现 rpc 调用

### ISSUE THREAD

**Issue by heyuanchao** [name5566/leaf#58]
目前想到的是使用原生的"net/rpc"，Leaf 有提供其他的方法吗？

**Comment by name5566** [comment]
这个目前并不支持。需要自己用 TCP 连接两个 Leaf 服务器。不过 Leaf 内部也做了一些辅助的工作，比如说 TCP 连接有自动重连，支持定义 RawHandler 来实现消息的自动分发等等。

**Comment by chiuan** [comment]
横批:自己琢磨当学习进阶..也不难
