### ISSUE TITLE
 open conf/server.json: The system cannot find the file specified.

### ISSUE THREAD

**Issue by jaimeyang** [name5566/leaf#59]
缺少了server.json的文件，能补充上来么？有些字段不知道什么意思

**Comment by name5566** [comment]
server.json 没有缺少，严格按照文档来操作应该就不会报错了。

**Comment by XEQTIONR** [comment]
running into same issue

`2020/10/30 00:25:51 [fatal  ] open conf/server.json: no such file or directory
exit status 1
`
