### ISSUE TITLE
关闭服务器的时候会报错

### ISSUE THREAD

**Issue by xieliujian** [name5566/leaf#60]
关闭服务器的时候会报错, 看报错是没有关闭客户端连接，这个应该是底层处理的吗
2017/10/28 17:33:19 [release] Leaf 1.1.2 starting up
tcp_msg->Read
2017/10/28 17:33:32 [release] Leaf closing down (signal: interrupt)
io.ReadFull(conn, bufMsgLen) error
2017/10/28 17:33:32 [debug  ] read message: read tcp 127.0.0.1:3563->127.0.0.1:7814: use of closed network connection

**Comment by name5566** [comment]
关闭服务器的时候，服务器会断开所有连接。

**Comment by xieliujian** [comment]
服务器主动关闭所有连接的话，就不应该报这个错了。
https://github.com/xieliujian/UnityGameFramework 这个是我前后端的工程

**Comment by name5566** [comment]
这个不是报错，是一个提示，release 下不存在这个提示信息，这个提示是 leaf 输出的。

**Comment by xieliujian** [comment]
好的，谢谢，我在学习下。
