### ISSUE TITLE
Leaf cluster options

### ISSUE THREAD

**Issue by imilo** [name5566/leaf#69]
Hello,
Repo contains a **cluster** dir/code. Short code exploring says it's to create a cluster from different Leaf nodes. Unfortunately documentation doesn't provide any info about that.

Can you describe how does it work (now and in the future), what information is being shared? It will help to understand the technology and to achieve a better performance with hardware scaling.

Would be nice to see this info in the documentation too, even if it's not completely ready yet.

Thanks!

**Comment by name5566** [comment]
Sorry, I haven't implemented it yet. The cluster will not implement soon.
