### ISSUE TITLE
求增加对binary类型的msg处理

### ISSUE THREAD

**Issue by guowh** [name5566/leaf#7]
由于项目里没用用json和protobuf，用的是二进制的通信格式，急迫需要binary类型的处理，求增加此类型。

**Comment by name5566** [comment]
消息包的格式为：
| len | data |
这个格式是固定的。data 能够按照 JSON 或者 Protobuf 来解析。现在需要自定义 data 的解析方式，是吗？

**Comment by guowh** [comment]
对，对于data的具体格式，应该是谁来定义，谁来解析，我看服务端根据len读取到data后，通过反射得到data的类型，如果data本身就是一个二进制的序列化内容，非json格式，非protobuf类型，希望也能route到对应的消息格式里处理。

**Comment by joneshan** [comment]
这次改动 已经影响了之前版本的兼容性了吧？  我的代码都辩不过了

**Comment by name5566** [comment]
2 年前的改动且影响很小。你的版本太低了吧，建议升级一下

**Comment by joneshan** [comment]
哦哦  好的  升级了   发现咋收不到消息了  也没有任何报错。。。
