### ISSUE TITLE
谁能给一个leaf+protobuf的具体的例子，包括go客户端测试

### ISSUE THREAD

**Issue by PurpleVampire** [name5566/leaf#72]

**Comment by PurpleVampire** [comment]
文档有详细的json的例子，自己也实现成功，为什么protobuf的略过了，自己写，怎么也不成功，求增加一个protobuf的详细的例子

**Comment by lifang218c** [comment]
yeah ， i also need a example。 who can help us？ 嗯嗯 是的 我参考文档在服务端编写好了 但是客户端不知道怎么调用。。这就尴尬了

**Comment by yiippee** [comment]
func main() {
	conn, err := net.Dial("tcp", "127.0.0.1:3564")
	if err != nil {
		panic(err)
	}
	test := &msg.Hello{
		// 使用辅助函数设置域的值
		Name: *proto.String("Leaf"),
	}
	// 进行编码
	data, err := proto.Marshal(test)
	if err != nil {
		fmt.Println("marshaling error: ", err)
	}
	// len + id + data
	m := make([]byte, 4+len(data))
	binary.BigEndian.PutUint16(m, uint16(len(data) + 2))
	copy(m[4:], data)
	// 发送消息
	conn.Write(m)
}

**Comment by exfun** [comment]
最近公司做H5游戏，websocket protobuf实现附上。需要的可以看看
https://github.com/exfun/leaf-client-ws/
