### ISSUE TITLE
建议：增加websocket认证回调

### ISSUE THREAD

**Issue by karllynnn** [name5566/leaf#74]
ws server采用HTTP认证然后再upgrade建立长连接是比较常见的做法，建议在`ws_server`的`ServeHTTP`方法里面增加HTTP认证回调功能，如果认证失败，直接断开连接。

**Comment by karllynnn** [comment]
就是另外有HTTP的登录服务器，这边ws连接的时候直接把userId和token传过来做校验就可以了

**Comment by karllynnn** [comment]
大概就是在upgrade到ws协议之前，允许用户验证http参数，如下：

```go
func (handler *WSHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    if r.Method != "GET" {
        http.Error(w, "Method not allowed", 405)
        return
    }
    //增加回调
    if !CheckAuth(r, w){
	//……
	return
    }
    conn, err := handler.upgrader.Upgrade(w, r, nil)
    if err != nil {
        log.Debug("upgrade error: %v", err)
        return
    }
}
```

**Comment by name5566** [comment]
如果是这个逻辑，那么完全可以做到 ws 连接成功以后，通过 ws 发送消息来验证身份的。

**Comment by karllynnn** [comment]
理论上可以的，但是这样可能会被人恶意连接，占满最大连接数。

所以我们想还是在连接的时候直接认证最好…嗯，只是提个建议，仅供参考哈

**Comment by name5566** [comment]
leaf 的设计思路是，底层网络是可以随意替换的，也就是底层使用 ws 还是用 tcp 或者是 udp，对于上层开发者是完全透明的，所以接口是一个通用接口。因此，我们可以看到，leaf 的服务器可以同时被 ws 和 tcp 客户端连接，且这些客户端之间可以自由交互。

客户端做验证是一个逻辑，然后客户端真正和游戏服务器连接是另外一个逻辑。例如，客户端和认证服务器交互获得一个 token，然后这个 token 被发送到游戏服务器，客户端通过这个 token 和游戏服务器确认身份。验证和游戏逻辑通常不会在一个服务器上（很多时候，用户身份认证不是自己的服务器，而是第三方的服务器），所以一般也不存在你说的问题。

**Comment by karllynnn** [comment]
好的，嗯…这样确实打破了这种透明性，那我这边再想办法把，谢谢：）

**Comment by name5566** [comment]
:)
