### ISSUE TITLE
考虑增加消息处理中间件？

### ISSUE THREAD

**Issue by karllynnn** [name5566/leaf#75]
hello，在使用的过程中，有时候发现需要对客户端发来的消息做一些统一处理，比如某个消息的请求日志之类的，感觉没有什么特别好的办法，目前是在函数入口统一调用某个函数。感觉可以考虑增加中间件类的消息处理，如`beforeProcess`, `afterProcess`之类的

**Comment by karllynnn** [comment]
我知道还有种方法是把所有需要处理的消息映射到同一个函数，处理以后再用`switch args[0].(type)`来二次分发，但是感觉也不是很优雅…

**Comment by name5566** [comment]
你可以参考一下 https://github.com/name5566/leaf/issues/41

**Comment by karllynnn** [comment]
好的，感谢~
