### ISSUE TITLE
麻烦换下自带的mgo数据库引擎

### ISSUE THREAD

**Issue by IT-Pianist** [name5566/leaf#76]
自带的mgo数据库引擎遇到非string为key的map解析不了。mgov2作者已经给到社区维护
github.com/globalsign/mgo社区维护的这个包，是可以用的。

**Comment by name5566** [comment]
这个有影响接口吗？

**Comment by IT-Pianist** [comment]
接口无影响，但是leaf引用了这个包。

**Comment by name5566** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
建议先自己替换掉。



        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by 15951836388** [comment]
确实有这个问题，map的key只能是string，用起来不方便。
这个包还还有什么其他改进吗？

**Comment by name5566** [comment]
建议需要的自己更换。

**Comment by 15951836388** [comment]
我已经换了，非常好用，支持map 的int类型key 建议leaf更换 @name5566
