### ISSUE TITLE
遇到迷之bug：RegisterCommand无效

### ISSUE THREAD

**Issue by karllynnn** [name5566/leaf#77]
在使用`go build`编译以后，运行的时候，有时候telnet连上去，是有自己定义的指令的，但是有时候没有，只有内置的几个指令，非常迷。

代码一行也不用改，用dlv debug也能看到正常注册进去。整体格式是仿照wiki文档里面，在全局声明skeleton，在init函数里面RegisterCommand.

暂时没什么思路，好在影响不大。发出来看有人能提供以下思路么…

**Comment by amsalt** [comment]
有没有可能是你的N(>=2)个进程在不断的重启
