### ISSUE TITLE
我用Leaf的WS向微信发送消息，请问怎么默认发送数据格式为String或者ArrayBuffer，而不是默认的Blob

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#80]
如题，谢谢回答

**Comment by jjjjilyf** [comment]
看了一下例子19能不能让服务器不发送二进制的数

**Comment by jjjjilyf** [comment]
不应该是返回String或者ArrayBuffer吗？

**Comment by name5566** [comment]
可以先参考一下：https://github.com/name5566/leaf/issues/19

**Comment by jjjjilyf** [comment]
谢谢大哥指点，#19已经看了，那个Decoder在微信官方上说不支持。
最后问题解决了，用了一个String.fromCharCode.apply(null, new Uint8Array(buf));直接转换就出来了。
哎 I am really a bad joke
