### ISSUE TITLE
leaf里面各个模块是单线程吗，比如login，game模块

### ISSUE THREAD

**Issue by www1wj** [name5566/leaf#83]

**Comment by cheekey** [comment]
多线程的，看见锁了!
type WSHandler struct {
	maxConnNum      int
	pendingWriteNum int
	maxMsgLen       uint32
	newAgent        func(*WSConn) Agent
	upgrader        websocket.Upgrader
	conns           WebsocketConnSet
	mutexConns      sync.Mutex
	wg              sync.WaitGroup
}

**Comment by name5566** [comment]
单线程
