### ISSUE TITLE
请问mongodb的连接例子里db.Ensure.Counter("game", "counters", "users")起的什么作用

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#85]
db.EnsureCounter("game", "counters", "users")
是创建了counters表，然后把users表名放到counter表里吗？这里的users是不是指的具体玩家名字还是users表名呢？如果是放玩家的数据，users表里不是已经存了吗？如果就放users这个表名，有什么意义吗？谢谢解答。

// users
	err = db.EnsureUniqueIndex("game", "users", []string{"accid"})
	if err != nil {
		log.Fatal("ensure index error: %v", err)
	}
	err = db.EnsureCounter("game", "counters", "users")
	if err != nil {
		log.Fatal("ensure counter error: %v", err)
	}

**Comment by jjjjilyf** [comment]
看了底层的源码是调用了 isDup这个函数，但是id重复了不是该返回err吗，怎么重复了却返回nil？接下来处理是if err != nil，这样的话 不就是不重复吗？不重复 却要打印，是不是这里并没有提供错误的处理方式，只是单纯的打印一下err内容呢？
func (c *DialContext) EnsureCounter(db string, collection string, id string) error {
	s := c.Ref()
	defer c.UnRef(s)

	err := s.DB(db).C(collection).Insert(bson.M{
		"_id": id,
		"seq": 0,
	})
	if mgo.IsDup(err) {
		return nil
	} else {
		return err
	}
}

**Comment by name5566** [comment]
EnsureCounter 是为某个 collection 创建一个 counter。IsDup 表示，如果已经创建好了 counter，就不需要重复创建了，也就是这是正常情况，而非错误。

**Comment by jjjjilyf** [comment]
谢谢回答，这个counter表里存放的是什么数据呢？

**Comment by name5566** [comment]
这个是用来实现自增长 ID 的。

**Comment by jjjjilyf** [comment]
好的 刚刚接触mongodb，我再看看，谢谢大神
