### ISSUE TITLE
MongoDB建立连接成功，在执行代码查询代码时，报没有权限，且直接退出服务。

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#86]

**Comment by jjjjilyf** [comment]
在服务器mongod下，创建了数据库piggy,use admin,创建了用户root，root有userAdminAnyDatabase权限
db.createUser({user:"root", pwd:"root", roles:[
{role:"readWrite", db:"admin"},
{role:"dbAdmin", db:"admin"},
{role:"readWrite", db:"piggy"},
{role:"dbAdmin", db:"piggy"},
{role:"userAdminAnyDatabase", db:"admin"},
]})

然后关闭mongod
用mongod --auth --port 27017 /data/db开启服务，
用mongo登录
db.auth("root", "root")登录
然后use piggy(数据库)
db.createUser({user:"piggy", pwd:"piggy", roles:[{role:"readWrite", db:"piggy"}]})
然后用重开一个终端，使用db.auth("piggy", "piggy")登录。
==================================重点来了。
我在新开的终端这里可以运行 插入，创建createIndex,find等db命令，正常运行。
但是在Leaf里"DBUrl": "mongodb://piggy:piggy@127.0.0.1:27017/piggy",登录进去无论执行什么命令 都报没有权限，包括最基本的find命令。求教一下。
而且，在执行一次查询后，这个Leaf服务端就退出服务了。

**Comment by name5566** [comment]
直接使用外部工具，使用相同用户执行相同命令试试

**Comment by jjjjilyf** [comment]
谢谢大神回答，我觉得可能是那个原因，就是连接成功后，它默认的还在test数据库下，而不是piggy下，虽然连接的是piggy，但是连接成功后，仍然在test下，在test下执行命令就不成功了，但是还没找到办法，怎么让他连接成功后，自动去use piggy

**Comment by jjjjilyf** [comment]
运行完就退出那个问题找到了，是因为我用了log.Fatal打印

**Comment by jjjjilyf** [comment]
我就是按照你说的这种，刚开始我是用mongod,use piggy,db.auth这样的登录的，
后面直接用mongo -u -p --authenticationDatabase "piggy"这样一次性登录的，就发现了登录后直接就在test数据库下

**Comment by name5566** [comment]
使用适当的 mongodb uri 可以解决你的问题

**Comment by jjjjilyf** [comment]
在看https://docs.mongodb.com/manual/reference/connection-string/index.html#connections-connection-options官网的选项，还没看到有效的option

**Comment by jjjjilyf** [comment]
自己解决了
