### ISSUE TITLE
请问使用Leaf 用protobuf 传输数据数据过大，socket发生粘包，拆包，怎么处理？

### ISSUE THREAD

**Issue by cdcailf** [name5566/leaf#89]

**Comment by xtutu** [comment]
有两个变量影响包体大小
在 conf.go 文件里面
1. MaxMsgLen
2. LenMsgLen

**Comment by cdcailf** [comment]
谢谢您回复，但是是由于服务器发的包太大，客户端发生粘包和拆包，服务器需要做什么吗？每次把消息拆分小包再发送？

**Comment by name5566** [comment]
这不是上层逻辑开发需要考虑的问题。如果你想知道实现细节请看源码。

**Comment by mrluoming** [comment]
tcp粘包和拆包需要考虑 源码貌似没有相关处理
