### ISSUE TITLE
time

### ISSUE THREAD

**Issue by IT-Pianist** [name5566/leaf#93]
timer的实现有BUG，如果在主groutine中调用stop停止timer，此时如果time的刚好在stop之前触发，那么此时time还是会被提交到Dispatcher的chan中。继续执行会导致空指针。

**Comment by name5566** [comment]
具体哪个是空指针了？

**Comment by cdcailf** [comment]
不应该在自己的逻辑先判断timer是否为nil吗？ @IT-Pianist

**Comment by trist725** [comment]
我也遇到了，AfterFunc返回的timer指针可能会是nil,因此导致难以正常调用timer.stop()   @name5566

**Comment by name5566** [comment]
能否提供简单的可以重现的测试用例？

**Comment by sunanxiang** [comment]
```
if !t.Stop() {
    <-t.C
}
t.Stop
```
正常使用方法应该是上面的吧。

**Comment by cokeboL** [comment]
标准库的time.AfterFunc会起一个协程，游戏定时器较多的场景，尤其是短时间内大量触发的时候，这个开销很大
建议废弃当前这个timer吧，之前给cellnet作者说过，这种简单的包装，没什么意义
高性能的通常就两种实现：
1. 堆，可以实现高性能高精度单协程低消耗，但是要处理好线头阻塞
2. 时间轮，性能好但是精度差一些

**Comment by name5566** [comment]
这个封装是必须的。你需要理解 Leaf 的结构和设计思路。

**Comment by 15951836388** [comment]
不过timer确实可以改成时间轮，性能好

**Comment by name5566** [comment]
目前对于特殊的定时功能是存在优化的空间，比如说，50ms 执行一次某个函数。但是 timer 本身很难优化。

**Comment by cokeboL** [comment]
> 目前对于特殊的定时功能是存在优化的空间，比如说，50ms 执行一次某个函数。但是 timer 本身很难优化。

用堆和时间轮是数据结构层面的，封装出来的接口都可以整合到框架里，跟leaf的结构没关系

**Comment by name5566** [comment]
> > 目前对于特殊的定时功能是存在优化的空间，比如说，50ms 执行一次某个函数。但是 timer 本身很难优化。
> 
> 用堆和时间轮是数据结构层面的，封装出来的接口都可以整合到框架里，跟leaf的结构没关系

Leaf 的定时器回调函数是在主 goroutine 中执行的。封装定时器解决的是整个问题。

**Comment by 15951836388** [comment]
他的意思，是把leaf封装的timer里的那个《系统timer》的换成时间轮来实现，提高了性能，且不破坏leaf原来的结构

**Comment by name5566** [comment]
> 他的意思，是把leaf封装的timer里的那个《系统timer》的换成时间轮来实现，提高了性能，且不破坏leaf原来的结构

关键是，Leaf 的结构要求必须存在这个额外的 goroutine。

**Comment by 15951836388** [comment]
那时间轮的实现也开开个额外的 goroutine才行了吧？

**Comment by name5566** [comment]
> 那时间轮的实现也开开个额外的 goroutine才行了吧？

通常来说是这样的。细想其实问题不少。最简单的设计，通常不会是最差的设计。

**Comment by 15951836388** [comment]
有道理，性能开销不大的话，已经够用了

**Comment by cokeboL** [comment]
> 那时间轮的实现也开开个额外的 goroutine才行了吧？

额外的协程是必须的，但是一个时间轮只需要一个额外的协程，开销很小

time.AfterFunc就不同了，你们看一下源码，每次触发回调都会新起一个协程，所以在大量定时器短期触发的场景，开销就不划算了

**Comment by name5566** [comment]
实际上实现不好处理。官方的做法，回调函数在额外的一个 goroutine 执行，这样执行对定时器没有任何干扰，对其他回调函数的执行也没有干扰，是最通用的做法。

**Comment by name5566** [comment]
当然，这个问题对于 Leaf 的特定用法又是一个特殊的存在。但个人感觉，还没有必要为了不太清楚的性能问题，引入过度复杂的设计。

**Comment by cokeboL** [comment]
> 当然，这个问题对于 Leaf 的特定用法又是一个特殊的存在。但个人感觉，还没有必要为了不太清楚的性能问题，引入过度复杂的设计。

^_^
