### ISSUE TITLE
请问TCPConn里为什么len(tcpConn.writeChan) == cap(tcpConn.writeChan)之后就要把tcpConn销毁

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#95]
func (tcpConn *TCPConn) doWrite(b []byte) {
	if len(tcpConn.writeChan) == cap(tcpConn.writeChan) {
		log.Debug("close conn: channel full")
		tcpConn.doDestroy()
		return
	}

	tcpConn.writeChan <- b
}

// b must not be modified by the others goroutines
func (tcpConn *TCPConn) Write(b []byte) {
	tcpConn.Lock()
	defer tcpConn.Unlock()
	if tcpConn.closeFlag || b == nil {
		return
	}

	tcpConn.doWrite(b)
}

**Comment by jjjjilyf** [comment]
channal full的时候，不是应该等待被读取就行了吗？为什么要把整个tcpConn都销毁掉？销毁掉不是和客户端断开连接了吗？

**Comment by name5566** [comment]
出于几点考虑：
1. 如果连接一直不能接收消息，通常是连接有问题了，应该断开
2. 一种保护机制，如果连接一直不接收消息，消息会在服务器不断堆积，不断消耗服务器的内存，这是不合理的

**Comment by jjjjilyf** [comment]
3Q
