### ISSUE TITLE
请问下leaf_cluster实现了集群功能吗？怎么找不到哪里有实现了集群的功能？

### ISSUE THREAD

**Issue by jjjjilyf** [name5566/leaf#97]
谢谢回答

**Comment by name5566** [comment]
leaf 不支持集群

**Comment by jjjjilyf** [comment]
谢谢回答，但是在这个Issues #10里看到你做的这个回答啊 大哥 https://github.com/name5566/leaf/issues/10

name5566 commented Aug 17, 2017
可以参考 @zsai001 的版本：https://github.com/zsai001/leaf_cluster

**Comment by jjjjilyf** [comment]
还有顺便问一下，能不能一个Gate，一个Login，多个Game服务器 该怎么配置呢？

**Comment by name5566** [comment]
@zsai001 的 cluster 版本貌似没有怎么更新。Leaf 可以做出多个服务器的，但是需要对 Leaf 更加深入了解，难度比直接使用大。

**Comment by jjjjilyf** [comment]
3Q for your reply
